# Generated by Django 3.0.2 on 2020-02-20 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0002_auto_20200216_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='EloRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('abbreviation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.Team')),
            ],
        ),
    ]
