# Generated by Django 3.0.2 on 2020-02-20 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0003_elorating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elorating',
            old_name='abbreviation',
            new_name='team',
        ),
    ]
