# Generated by Django 3.0.2 on 2020-02-20 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_auto_20200219_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elorating',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='elo_rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='elo.EloRating'),
            preserve_default=False,
        ),
    ]
