# Generated by Django 3.0.2 on 2020-02-24 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0005_auto_20200219_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='elo_rating',
        ),
        migrations.AddField(
            model_name='elorating',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='elo.Team'),
        ),
    ]
